version: '2'
services:
  jenkins:
    image: vyrphan/jenkins-amd64:2.73.2
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./jenkinshome:/var/jenkins_home"
