version: '2'
services:
  db:
    image: arm32v7/postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
      - POSTGRES_DB=gogs
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  gogs:
    image: vyrphan/gogs-arm32v7:0.11.29
    restart: always
    ports:
      - "3000:3000"
      - "2232:2232"
    volumes:
      - "./git:/root/gogs-repositories"
      - "./logs:/code/gogs/log"
    environment:
      - USER=root
      - USERNAME=root
    links:
      - db
    depends_on:
      - db
  drone-server:
    image: drone/drone:0.7
    ports:
      - "8000:8000"
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_SECRET=${DRONE_SECRET}
  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
