version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
      - POSTGRES_DB=gogs
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  gogs:
    image: vyrphan/gogs-amd64:0.11.29
    restart: always
    ports:
      - "3000:3000"
      - "2232:2232"
    volumes:
      - "./git:/root/gogs-repositories"
      - "./logs:/code/gogs/log"
    environment:
      - USER=root
      - USERNAME=root
    links:
      - db
    depends_on:
      - db
